name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: Check formatting, linting, types and run tests
        run: deno task ok

      - name: Publish (dry-run)
        run: deno publish --dry-run --allow-dirty
